apps/blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
	path('', views.blog_list, name='blog_list'),
	path('blog_category/<int:blog_category_id>/', views.get_blog_with_category, name='get_blog_with_category'),
	path('date/<int:year>/<int:month>/', views.get_blog_with_date, name='get_blog_with_date'),
	path('<int:blog_pk>/', views.blog_detail, name='blog_detail'),
]

simpleBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('admin/', admin.site.urls, name='source_admin'),
    path('search/', include('haystack.urls')),  # haystack搜索
    # path("ckeditor", include("ckeditor_uploader.urls")),  # has been used
    path('mdeditor/', include('mdeditor.urls')),
    path('', views.home, name='home'),
    path('blog/', include('apps.blog.urls')),
    path('users/', include('apps.targetauth.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blog/models.py
from django.db import models
# from django.contrib.auth.models import User  # use new User
from apps.targetauth.models import User
# from ckeditor_uploader.fields import RichTextUploadingField  # used ckeditor
from apps.read_statistics.Mixin import ReadTimeExpandMixin
from apps.read_statistics.models import ReadDetail
from django.contrib.contenttypes.fields import GenericRelation
from mdeditor.fields import MDTextField


class BlogCategory(models.Model):
	type_name = models.CharField(verbose_name="博客分类", max_length=10)

	def __str__(self):
		return self.type_name

	class Meta:
		verbose_name = "博客分类"
		verbose_name_plural = "博客分类"


class Blog(models.Model, ReadTimeExpandMixin):
	title = models.CharField(verbose_name="标题", max_length=50)
	content = MDTextField(verbose_name="内容")
	author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="作者")
	create_time = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)
	last_updated_time = models.DateTimeField(verbose_name="最后更新时间", auto_now=True)
	type_name = models.ForeignKey("BlogCategory", on_delete=models.CASCADE, verbose_name="博客分类")
	# ReadDetail使用了contenttype将Blog和自身关联，这里可以使用GenericRelation来翻转获得信息
	# 注意， 不用迁移数据库
	read_details = GenericRelation(ReadDetail, verbose_name="访问详情")

	def __str__(self):
		return "<blog>: {}".format(self.title)

	class Meta:
		verbose_name = "博客"
		verbose_name_plural = "博客"
		ordering = ['-create_time']

apps/blog/views.py
import mistune
from django.shortcuts import render, get_object_or_404
from .models import Blog, BlogCategory
from django.core.paginator import Paginator
from django.conf import settings
from utils.read_statistic_method import read_statistic_once_by_cookies


def get_blog_list_common_data(request, blogs):
	"""
	根据传入来的QuerySet对象blogs进行分页
	:param request: 原样请求
	:param blogs: QuerySet对象
	:return: dict() 有以下键值对
		"blogs": Page() 根据request.GET获得查询字符串page获得的实际的Page对象
		"blog_categoryes": QuerySet 获得全部的BlogCategory，对字段blog_set进行懒惰查询处理，后期可以添加缓存中进行处理(几乎都要用到)
		"arround_page_num": list() 根据当前页索引，设置左右范围
		"blog_dates": dict() 根据降序的月份作为键，对应月份的博客数作为值
	"""
	paginator = Paginator(blogs, settings.PAGE_NUM)  # 10是一页多少项
	page_num = request.GET.get("page", 1)  # 需要查找第几页，默认1
	page = paginator.get_page(page_num)  # 实际的页，内容是models， 无需关心page_num是否字符串或数字

	paginator_page_range = paginator.page_range  # 页面的区间，返回range(), 如果有三页，则返回range(1,4)
	paginator_num_pages = paginator.num_pages  # 一共可以分成多少页

	# 根据当前页，设置左右页码索引
	# 假设左右n(page.number-NEAR_RANGE)个，则一共2n+1个页， 页码索引要求从1到最后
	# 要求i在页码区间内，不然会出现负数啥的
	arround_page_num = [i for i in range(page.number - settings.NEAR_RANGE,
	                                     page.number + settings.NEAR_RANGE + 1) if i in paginator_page_range]

	# 加上省略页码
	if arround_page_num[0] >= settings.NEAR_RANGE:  # 如果首个值大于范围最小，则添加省略页码
		arround_page_num.insert(0, "...")
	if arround_page_num[-1] <= paginator_num_pages - settings.NEAR_RANGE + 1:  # 如果最大值小于范围最大
		arround_page_num.append("...")

	# 加上首页和尾页
	if arround_page_num[0] != 1:  # 如果不是从1开始，则添加首页1
		arround_page_num.insert(0, 1)
	if arround_page_num[-1] != paginator_num_pages:  # 如果末尾不是最后一页，添加末尾页
		arround_page_num.append(paginator_num_pages)

	# 按照时间算博客篇数
	blog_dates = Blog.objects.dates("create_time", "month", order="DESC")  # 获得降序的月份
	blog_dates_dict = dict()
	for blog_date in blog_dates:
		blog_count = Blog.objects.filter(create_time__year=blog_date.year,  # 按照datetime__对应属性=blog_date对应属性
		                                 create_time__month=blog_date.month).count()
		blog_dates_dict[blog_date] = blog_count

	context = {
		"blogs": page,
		"blog_categories": BlogCategory.objects.all().prefetch_related("blog_set"),  # 博客分类。提前缓存
		"arround_page_num": arround_page_num,
		"blog_dates": blog_dates_dict,
	}
	return context


def blog_list(request):
	"""
	初始博客列表
	:param request:
	:return:
	"""
	blogs = Blog.objects.all()
	context = get_blog_list_common_data(request, blogs)
	return render(request, "blog/blog_list.html", context=context)


def get_blog_with_category(request, blog_category_id):
	"""
	根据分类获得的博客列表
	:param request:
	:param blog_category_id:
	:return:
	"""
	blog_type = get_object_or_404(BlogCategory, pk=blog_category_id)  # 根据查询字符串获得分类

	blogs = Blog.objects.filter(type_name=blog_type)

	context = get_blog_list_common_data(request, blogs)

	return render(request, 'blog/blog_list.html', context)


def get_blog_with_date(request, year, month):
	"""
	根据日期获得博客列表
	:param request:
	:param year:
	:param month:
	:return:
	"""
	blogs = Blog.objects.filter(create_time__year=year, create_time__month=month)  # 根据查询字符串获得博客QuerySet
	context = get_blog_list_common_data(request, blogs)

	return render(request, 'blog/blog_list.html', context)


def blog_detail(request, blog_pk):
	blog = get_object_or_404(Blog, pk=blog_pk)  # get_object_or_404： get or raise 404 exception
	# 给阅读数加一
	read_statistic_once_by_cookies(request, blog)

	# 将markdown渲染为html
	# mark = mistune.Markdown()
	# blog.content = mark(blog.content)

	context = {
		# Blog是倒序的，找到前一篇就是找比当前博客时间早的， 选集合中的最后一篇
		'previous_blog': Blog.objects.filter(type_name=blog.type_name, create_time__gt=blog.create_time).last(),
		# Blog是倒序的，找到后一篇就是找比当前博客时间晚的，选集合中的第一篇
		'next_blog': Blog.objects.filter(type_name=blog.type_name, create_time__lt=blog.create_time).first(),
		'blog': blog,
	}

	# 设置cookies
	response = render(request, 'blog/blog_detail.html', context)
	response.set_cookie("blog_{}_read".format(blog_pk), "true")  # 浏览器关闭即删除cookies
	return response

front/templates/blog/blog_detail.html
{% extends 'base.html' %}

{% block title %}
    标题: {{ blog.title }}
{% endblock %}

{% block header %}
    <link rel="stylesheet" href="{% static 'css/blog/blog_detail.css' %}">

    <link rel="stylesheet" href="{% static 'editor.md/css/editormd.min.css' %}">
{#    <link rel="stylesheet" href="{% static  "editor.md/css/editormd.preview.min.css" %}">#}
{#    <link rel="stylesheet" href="{% static 'editor.md/css/editormd.logo.min.css' %}">#}

    <script type="text/javascript" src="{% static  'editor.md/lib/marked.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'editor.md/lib/prettify.min.js' %}"></script>

{#    <script type="text/javascript" src="{% static 'editor.md/lib/raphael.min.js' %}"></script>#}
{#    <script type="text/javascript" src="{% static 'editor.md/lib/underscore.min.js' %}"></script>#}
{#    <script type="text/javascript" src="{% static 'editor.md/lib/sequence-diagram.min.js' %}"></script>#}
{#    <script type="text/javascript" src="{% static 'editor.md/lib/flowchart.min.js' %}"></script>#}
{#    <script type="text/javascript" src="{% static 'editor.md/lib/jquery.flowchart.min.js' %}"></script>#}

    <script type="text/javascript" src="{% static 'editor.md/js/editormd.min.js' %}"></script>

{% endblock %}

{% block body-content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1">
                <h1>{{ blog.title }}</h1>
                <ul class="_blog-desc">
                    <li>作者: {{ blog.author.username }}</li>
                    <li>发表时间: {{ blog.create_time | date:"Y-m-d H:i:s" }}</li>
                    <li>分类: <a
                            href="{% url 'blog:get_blog_with_category' blog_category_id=blog.type_name.pk %}">{{ blog.type_name }}</a>
                    </li>
                    <li>阅读数: {{ blog.get_read_times }}</li>
                </ul>
                <div class="_blog_content">

                    <div id="editormd-show" class="editormd-html-preview" style="width: 90%;">  <!-- 纯粹的显示器 -->
                        <textarea style="display:none;">
                             {{ blog.content }}
                        </textarea>
                    </div>
                </div>
                <div class="_blog_more">


                    {% if previous_blog %}


                        <a href="{% url 'blog:blog_detail' blog_pk=previous_blog.pk %}">
                        <button type="button" class="btn btn-primary pull-right"> {{ previous_blog.title }}</button>

                        </a>
                    {% else %}

                        <button type="button" class="btn btn-primary disabled pull-right">没有了</button>

                    {% endif %}
                    {% if next_blog %}
                        <a href="{% url 'blog:blog_detail' blog_pk=next_blog.pk %}">
                        <button type="button" class="btn btn-info pull-right">{{ next_blog.title }}</button>

                        </a>
                    {% else %}

                        <button type="button" class="btn btn-info disabled pull-right">没有了</button>

                    {% endif %}
                </div>
            </div>
        </div>
    </div>


{% endblock %}

{% block js-script %}
    <script type="text/javascript">
        $(function () {
            var EditormdView = editormd.markdownToHTML("editormd-show", {});
        });
    </script>
{% endblock %}

front/templates/blog/blog_list.html
{% extends 'base.html' %}

{% block title %}
    猫叹息道 | 博客列表
{% endblock %}

{% block header %}
    <link rel="stylesheet" href="{% static 'css/blog/blog_list.css' %}">
{% endblock %}

{% block body-content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-md-9 col-lg-10">
                <div class="panel panel-default">
                    <div class="panel-heading">个人博客</div>
                    <div class="panel-body">
                        {% for blog in blogs %}
                            <div class="_blog-body">
                                <h3><a href="{% url 'blog:blog_detail' blog_pk=blog.pk %}">{{ blog.title }}</a></h3>
                                <p class="_blog-info">
                                    <span class="glyphicon glyphicon-tag"><a href="#">{{ blog.type_name.type_name }}</a></span>
                                    <span class="glyphicon glyphicon-time">{{ blog.create_time|date:"Y-m-d" }}</span>
                                    <span class="glyphicon glyphicon-user">阅读:{{ blog.get_read_times }}</span>
                                </p>
                                <p>{{ blog.content|striptags|truncatechars:50 }}</p>
                                <!-- striptags:网页格式去除 truncatechars:限制长度-->
                            </div>
                        {% empty %}
                            <div class="_blog_body">
                                <h3>暂无博客</h3>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div>
                    <nav aria-label="Page navigation">
                        <div class="_paginator">
                            <ul class="pagination">
                                {% if blogs.has_previous %}  <!-- page的函数， 如果还有上一页-->
                                    <li>
                                        <a href="?page={{ blogs.previous_page_number }}">   <!-- page函数 上一页的页数-->
                                            <span>&laquo;</span>
                                        </a>
                                        {% else %}
                                        <!-- 没有上一页，则无法点击 -->
                                    <li class="disabled">
                                    <span class="disabled">&laquo;</span>
                                {% endif %}
                                </li>

                                {% for page_num in arround_page_num %}  <!-- arround_page_num是一个list，页码范围-->
                                    {% if page_num == blogs.number %}  <!-- 如果遍历出来的某一页是当前页，则处于选中状态 -->
                                        <li class="active">
                                            <span>{{ page_num }}</span>  <!-- with lable(a)-->
                                        </li>
                                    {% else %}  <!-- 非选中页 -->
                                        {% if page_num == "..." %}
                                            <li class="disabled">
                                                <span class="disabled">...</span>
                                            </li>
                                        {% else %}  <!-- 正常页码 -->
                                            <li><a href="?page={{ page_num }}">{{ page_num }}</a></li>
                                        {% endif %}
                                    {% endif %}
                                {% endfor %}

                                <!-- 判断是否还有后一页 -->
                                {% if blogs.has_next %}
                                    <li><a href="?page={{ blogs.next_page_number }}">
                                        <span>&raquo;</span>
                                    </a>  <!-- 获得下一页的页码-->
                                        {% else %}
                                    <li class="disabled">
                                    <span class="disabled">&raquo;</span>
                                {% endif %}
                                </li>
                            </ul>
                            <p>
                                共有{{ blogs.paginator.count }}博客  <!-- page.paginator的函数-->
                                当前{{ blogs.number }}页
                                共{{ blogs.paginator.num_pages }}页
                            </p>
                        </div>
                    </nav>
                </div>

            </div>
            <div class="hidden-xs col-sm-4 col-md-3 col-lg-2">  <!-- 超小屏幕隐藏 -->
                <div class="panel panel-default">
                    <div class="panel-heading">博客分类</div>
                    <div class="panel-body">
                        <ul>
                            {% for blog_category in blog_categories %}
                                <li class="list-group-item">
                                    <a href="{% url 'blog:get_blog_with_category'  blog_category_id=blog_category.pk %}">
                                        {{ blog_category.type_name }}({{ blog_category.blog_set.count }})
                                    </a>
                                </li>
                            {% empty %}
                                <li>
                                    暂无分类
                                </li>
                            {% endfor %}

                        </ul>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">日期归档</div>
                    <div class="panel-body">
                        <ul>
                            {% for blog_date, blog_count in blog_dates.items %}

                                <li class="list-group-item">
                                    <a href="{% url 'blog:get_blog_with_date' year=blog_date.year month=blog_date.month %}">
                                        {{ blog_date|date:"Y年m月" }}({{ blog_count }})
                                    </a>
                                </li>
                            {% endfor %}

                        </ul>
                    </div>
                </div>


            </div>
        </div>
    </div>
{% endblock %}