apps/blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
	path('', views.blog_list, name='blog_list'),
	path('blog_category/<int:blog_category_id>/', views.get_blog_with_category, name='get_blog_with_category'),
	path('date/<int:year>/<int:month>/', views.get_blog_with_date, name='get_blog_with_date'),
	path('<int:blog_pk>/', views.blog_detail, name='blog_detail'),
]

apps/targetauth/urls.py
from django.urls import path
from . import views


app_name = 'targetauth'

urlpatterns = [
	path('login/', views.LoginView.as_view(), name='login'),
	path('logout/', views.logout, name='logout'),
	path('token/', views.token),
]

simpleBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('admin/', admin.site.urls, name='source_admin'),
    path('search/', include('haystack.urls')),  # haystack搜索
    # path("ckeditor", include("ckeditor_uploader.urls")),  # has been used
    path('mdeditor/', include('mdeditor.urls')),
    path('', views.home, name='home'),
    path('blog/', include('apps.blog.urls')),
    path('users/', include('apps.targetauth.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

front/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- 设备优先-->
    <meta name='viewport' content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'sweetalert/sweetalert.css' %}">


    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'sweetalert/sweetalert.min.js' %}"></script>

    <script src="{% static 'js/csrf_ajax.js' %}"></script>
    <script src="{% static 'js/more_sweetalert.js' %}"></script>
    <script src="{% static 'js/message.js' %}"></script>

    {% block header %}{% endblock %}
</head>
<body>
<!-- navbar-fixed-top保持置顶-->
<header class="bs-docs-nav navbar navbar-static-top" id="top"></header> <!-- 返回顶部用 -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#target-content"> <!-- 页面小的时候将data-target指定id的内容隐藏，显示一个button -->
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>  <!-- 三条线-->
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">我的博客</a>
        </div>

        <!-- 页面小的时候会被隐藏 -->
        <div class="collapse navbar-collapse" id="target-content">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'home' %}">首页<span class="sr-only">(current)</span></a></li>
                <li><a href="{% url 'blog:blog_list' %}">博客</a></li>
            </ul>
            {% if user.is_authenticated %}
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false"> {{ user.username }}
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="/admin/">后台管理 </a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{% url 'targetauth:logout' %}">注销</a></li>
                        </ul>
                    </li>
                </ul>
            {% else %}
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="{% url 'targetauth:login' %}"> 登陆 </a>
                    </li>
                </ul>
            {% endif %}
        <!-- 搜索-->
            <form class="navbar-form navbar-right" action="/search">  <!-- /为根路径-->
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="输入要搜索的文章"
                           name="q" value={{ query }} >  <!-- query haystack保存上一次的搜索结果-->
                </div>
                <button type="submit" class="btn btn-default">搜索</button>
            </form>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->

</nav>

<!-- 右下角返回顶部 -->
<a href="#top" class="btn btn-default back-to-top" style="position: fixed; bottom: 50px; right:60px;"> Back to top </a>

{% block body-content %}{% endblock %}
{% block js-script %}{% endblock %}


</body>
</html>

front/templates/home.html
{% extends 'base.html' %}
{% block title %}
    猫叹息道
{% endblock %}

{% block header %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <!-- Highcharts可视化 https://www.hcharts.cn/docs/start-helloworld -->
    <script src="http://cdn.hcharts.cn/highcharts/highcharts.js"></script>
{% endblock %}

{% block body-content %}

    <h1 class="_home-content"><a href="{% url 'blog:blog_list' %}">个人博客</a></h1>
    <!-- 图表容器 DOM -->
    <div id="container"></div>
    <script>
        // 图表配置
        var options = {
            chart: {
                type: 'line'                        //指定图表的类型，默认是折线图（line）
            },
            title: {
                text: null                          // 标题
            },
            xAxis: {
                categories: {{ dates|safe }} ,  // x 轴分类
                title: {text: "七天阅读量变化"},
            },
            yAxis: {
                title: {
                    text: '阅读量'                   // y 轴标题
                },
                lables: {
                    enabled: false,
                },

            },
            series: [{                              // 数据列
                name: '阅读量',                        // 数据列名
                data: {{ read_statistics_total }}                // 数据
            }],
            legend: {
                enabled: false, //隐藏图例
            },
            credits: {
                enabled: false, // 隐藏右下角版权
            },
            plotOptions: {  // 开启数据标签
                line: {
                    dataLabels: {
                        enabled: true
                    }
                }
            }


        };
        // 图表初始化函数
        var chart = Highcharts.chart('container', options);
    </script>


    <div class="hidden-xs col-sm-4 col-md-4 col-lg-3 col-sm-offset-2 col-md-offset-2 col-lg-offset-3">  <!-- 超小屏幕隐藏 -->
        <div class="panel panel-default">
            <div class="panel-heading">今日访问量</div>
            <div class="panel-body">
                <ul>
                    {% for data in today_hot_data %}
                        <li class="list-group-item text-center">
                            <a href="{% url 'blog:blog_detail' blog_pk=data.content_object.pk %}">
                                《{{ data.content_object.title }}》({{ data.read_number }})
                            </a>
                        </li>
                    {% empty %}
                        <li class="list-group-item"> 暂无数据</li>
                    {% endfor %}

                </ul>
            </div>
        </div>
    </div>

    <div class="hidden-xs col-sm-4 col-md-4 col-lg-3">  <!-- 超小屏幕隐藏 -->

        <div class="panel panel-default">
            <div class="panel-heading">昨日访问量</div>
            <div class="panel-body">
                <ul>
                    {% for data in yesterday_hot_data %}
                        <li class="list-group-item text-center">
                            <a href="{% url 'blog:blog_detail' blog_pk=data.content_object.pk %}">
                                {{ data.content_object.title }}({{ data.read_number }})
                            </a>
                        </li>
                    {% empty %}
                        <li class="list-group-item"> 暂无数据</li>
                    {% endfor %}

                </ul>
            </div>
        </div>
    </div>

    <div class="hidden-xs col-sm-6 col-md-6 col-lg-4 col-sm-offset-3 col-md-offset-3 col-lg-offset-4 ">  <!-- 超小屏幕隐藏 -->

        <div class="panel panel-default">
            <div class="panel-heading">七天访问量</div>
            <div class="panel-body">
                <ul>
                    {% for blog in seven_days_hot_data %}
                        <li class="list-group-item text-center">
                            <a href="{% url 'blog:blog_detail' blog_pk=blog.id %}">
                                {{ blog.title }}({{ blog.read_number_total }})
                            </a>
                        </li>
                    {% empty %}
                        <li class="list-group-item"> 暂无数据</li>
                    {% endfor %}

                </ul>
            </div>
        </div>
    </div>
{% endblock %}